---
- name: Ubuntu AMI 하드닝 (CIS Benchmark 기반)
  hosts: all
  become: yes

  vars_files:
    - vars/cis-config.yml

  pre_tasks:
    - name: 모든 패키지 최신화
      apt:
        update_cache: yes
        upgrade: dist

  roles:
    - role: UBUNTU20-CIS  # GitHub에서 UNUTU20-CIS 설치

  tasks:

    # Python3 설치 (Ansible 모듈 사용 시 필요할 수 있음)
    - name: Python3 설치
      package:
        name: python3
        state: present

    # # CIS 하드닝에 따른 추가 작업이 있다면 아래 import로 처리
    # - import_tasks: cis-harden.yml

    - name: Install Trivy vulnerability scanner
      become: yes
      shell: |
        apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/trivy.list
        apt-get update
        apt-get install -y trivy

    - name: Run Trivy filesystem scan
      become: yes
      shell: |
        echo "[TRIVY] Starting filesystem scan..."
        trivy fs --severity HIGH,CRITICAL --exit-code 1 --no-progress /
      register: trivy_result
      ignore_errors: yes

    - name: Fail build if Trivy found critical vulnerabilities
      fail:
        msg: "Trivy scan found HIGH or CRITICAL vulnerabilities. AMI build aborted."
      when: trivy_result.rc != 0

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
